export default [
  {
    files: ["plugins/kusabi/scripts/**/*.mjs"],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "module",
      globals: {
        process: "readonly", console: "readonly", URL: "readonly",
        URLSearchParams: "readonly", setTimeout: "readonly", clearTimeout: "readonly",
        setInterval: "readonly", clearInterval: "readonly", queueMicrotask: "readonly",
        fetch: "readonly", Buffer: "readonly", AbortController: "readonly",
        AbortSignal: "readonly", TextEncoder: "readonly", TextDecoder: "readonly",
        structuredClone: "readonly", globalThis: "readonly", performance: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "error",
      "no-undef": "error",
      "no-unreachable": "error",
      "no-dupe-keys": "error",
      "no-dupe-args": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-const-assign": "error",
      "no-func-assign": "error",
      "no-import-assign": "error",
      "no-self-assign": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-constant-condition": "error",
      "no-fallthrough": "error",
      "no-cond-assign": "error",
      "no-empty": "error",
      "no-sparse-arrays": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
    },
  },
];
